#########################################
# The "development" compose file builds 
# the images locally
#########################################

version: "3.9"
services:
  apis:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DEBUG=$DEBUG
  nginx:
    build: 
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: always
    ports:
      - "80:80"


    